headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/anubhavmohandas/Documents/myprofile"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build needed'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*.jsx"

[headers.values]
Content-Type = "text/javascript"

[[headers]]
for = "/*.js"

[headers.values]
Content-Type = "text/javascript"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"